In [1]:
import numpy as np

In [43]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
# arr.append(6) error

In [44]:
arr = np.append(arr = arr, values = 6) # append 6 to end of the array 

In [45]:
arr

array([1, 2, 3, 4, 5, 6])

In [46]:
arr = np.delete(arr = arr, obj = 4) # delete the element at index 4

In [47]:
arr

array([1, 2, 3, 4, 6])

In [48]:
matrix = np.array([[1, 2, 3], [6, 7, 8], [1, 2, 2], [6, 7, 7]])

In [49]:
matrix

array([[1, 2, 3],
       [6, 7, 8],
       [1, 2, 2],
       [6, 7, 7]])

In [50]:
matrix2 = np.append(matrix, [[10, 20, 30]], axis =0)

In [51]:
matrix2

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 1,  2,  2],
       [ 6,  7,  7],
       [10, 20, 30]])

In [52]:
matrix.ndim

2

In [54]:
matrix2.shape

(5, 3)

In [65]:
matrix3 = np.append(matrix2, [[10], [11], [12], [14], [15]], axis = 1)

In [66]:
matrix3

array([[ 1,  2,  3, 10],
       [ 6,  7,  8, 11],
       [ 1,  2,  2, 12],
       [ 6,  7,  7, 14],
       [10, 20, 30, 15]])

In [76]:
mat4 = np.delete(matrix3, 2, axis = 0)

In [77]:
mat4

array([[ 1,  2,  3, 10],
       [ 6,  7,  8, 11],
       [ 6,  7,  7, 14],
       [10, 20, 30, 15]])

#### We can join (concatenate) multiple NumPy arrays

In [78]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

In [80]:
arr4 = np.concatenate((arr1, arr2, arr3))

In [81]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6]])

In [86]:
mat3 = np.concatenate((mat1,mat2))

In [87]:
mat3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
mat4 = np.array([[7], [8]])

In [97]:
mat5 = np.concatenate((mat1, mat4), axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [96]:
mat5

array([[1, 2, 7],
       [3, 4, 8]])