In [1]:
import numpy as np

In [2]:
empty_array = np.array(object = [])

In [3]:
empty_array

array([], dtype=float64)

In [5]:
type(empty_array) # data type of varibles

numpy.ndarray

In [7]:
empty_array.dtype # data type of elements

dtype('float64')

In [9]:
empty_array.ndim  # number of dimensions

1

In [11]:
empty_array.shape # shape of the array 

(0,)

In [13]:
empty_array.size # size of the array; counts all elements across dimensions

0

NumPy arrays with elements 

In [14]:
my_array = np.array([1, 2, 3, 4])

In [15]:
my_array

array([1, 2, 3, 4])

In [16]:
my_array.dtype

dtype('int64')

In [17]:
type(my_array)

numpy.ndarray

In [18]:
my_array.size

4

In [19]:
my_array.shape

(4,)

In [20]:
my_array.ndim

1

In [21]:
my_array = np.array([1.5, 2, 3])

In [22]:
my_array

array([1.5, 2. , 3. ])

In [23]:
my_array.dtype

dtype('float64')

In [24]:
my_array = np.array(['yes', 'no', 'available'])

In [25]:
my_array

array(['yes', 'no', 'available'], dtype='<U9')

other ways to create numpy arrays

In [27]:
np.arange(start = 1, stop = 40)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [28]:
np.arange(start = 1, stop = 40, step = 3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [32]:
np.array(range(1, 10, 3))

array([1, 4, 7])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros(2)

array([0., 0.])

In [36]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones(shape = 5, dtype=int)

array([1, 1, 1, 1, 1])

In [39]:
np.linspace(start = 2, stop = 3, num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [40]:
np.linspace( 4, 60, 9)

array([ 4., 11., 18., 25., 32., 39., 46., 53., 60.])

We can create multideimensional NumPy arrays

In [49]:
matrix = np.array([[1, 4, 5], [5, 6, 7], [2, 3, 4], [4, 7, 8]])

In [52]:
matrix

array([[1, 4, 5],
       [5, 6, 7],
       [2, 3, 4],
       [4, 7, 8]])

In [45]:
type(matrix)

numpy.ndarray

In [53]:
matrix.size

12

In [47]:
matrix.shape

(3, 3)

In [51]:
matrix.ndim

2

In [58]:
three_d_array = np.array([[[1, 2, 3], [6, 7, 8]], [[1, 2, 2], [6, 7, 7]]])

In [59]:
three_d_array

array([[[1, 2, 3],
        [6, 7, 8]],

       [[1, 2, 2],
        [6, 7, 7]]])

In [60]:
three_d_array.ndim

3

In [61]:
three_d_array.size

12

In [62]:
three_d_array.shape

(2, 2, 3)