In [1]:
import numpy as np

In [2]:
data = np.array([
    [25, 5000, 4.5, 1, 0],
    [45, 8000, 12.2, 0, 1],
    [35, 6000, 5, 1, 1],
])
data

array([[2.50e+01, 5.00e+03, 4.50e+00, 1.00e+00, 0.00e+00],
       [4.50e+01, 8.00e+03, 1.22e+01, 0.00e+00, 1.00e+00],
       [3.50e+01, 6.00e+03, 5.00e+00, 1.00e+00, 1.00e+00]])

In [3]:
#Scaling just the first three elements in each row

data[:, :3] = (data[:, :3] - data[:, :3].mean()) / data[:, :3].std() # standarding by subtracting the mean and dividing by the standard deviation
data

array([[-0.68599517,  0.93901389, -0.69269119,  1.        ,  0.        ],
       [-0.67946247,  1.91891885, -0.6901761 ,  0.        ,  1.        ],
       [-0.68272882,  1.26564888, -0.69252787,  1.        ,  1.        ]])

In [4]:
mat = np.array([[10, 20, 30], [40, 60, 50]])

In [5]:
mat

array([[10, 20, 30],
       [40, 60, 50]])

In [7]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [8]:
mat+ arr

array([[11, 22, 33],
       [41, 62, 53]])

In [9]:
mat/arr

array([[10.        , 10.        , 10.        ],
       [40.        , 30.        , 16.66666667]])