In [1]:
import numpy as np

In [2]:
empty_array = np.array(object = [])

In [3]:
empty_array

array([], dtype=float64)

In [5]:
type(empty_array) # data type of varibles

numpy.ndarray

In [7]:
empty_array.dtype # data type of elements

dtype('float64')

In [9]:
empty_array.ndim  # number of dimensions

1

In [11]:
empty_array.shape # shape of the array 

(0,)

In [13]:
empty_array.size # size of the array; counts all elements across dimensions

0

NumPy arrays with elements 

In [14]:
my_array = np.array([1, 2, 3, 4])

In [15]:
my_array

array([1, 2, 3, 4])

In [16]:
my_array.dtype

dtype('int64')

In [17]:
type(my_array)

numpy.ndarray

In [18]:
my_array.size

4

In [19]:
my_array.shape

(4,)

In [20]:
my_array.ndim

1

In [21]:
my_array = np.array([1.5, 2, 3])

In [22]:
my_array

array([1.5, 2. , 3. ])

In [23]:
my_array.dtype

dtype('float64')

In [24]:
my_array = np.array(['yes', 'no', 'available'])

In [25]:
my_array

array(['yes', 'no', 'available'], dtype='<U9')

other ways to create numpy arrays

In [27]:
np.arange(start = 1, stop = 40)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [28]:
np.arange(start = 1, stop = 40, step = 3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [32]:
np.array(range(1, 10, 3))

array([1, 4, 7])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros(2)

array([0., 0.])

In [36]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones(shape = 5, dtype=int)

array([1, 1, 1, 1, 1])

In [39]:
np.linspace(start = 2, stop = 3, num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [40]:
np.linspace( 4, 60, 9)

array([ 4., 11., 18., 25., 32., 39., 46., 53., 60.])

We can create multideimensional NumPy arrays

In [49]:
matrix = np.array([[1, 4, 5], [5, 6, 7], [2, 3, 4], [4, 7, 8]])

In [52]:
matrix

array([[1, 4, 5],
       [5, 6, 7],
       [2, 3, 4],
       [4, 7, 8]])

In [45]:
type(matrix)

numpy.ndarray

In [53]:
matrix.size

12

In [47]:
matrix.shape

(3, 3)

In [51]:
matrix.ndim

2

In [58]:
three_d_array = np.array([[[1, 2, 3], [6, 7, 8]], [[1, 2, 2], [6, 7, 7]]])

In [59]:
three_d_array

array([[[1, 2, 3],
        [6, 7, 8]],

       [[1, 2, 2],
        [6, 7, 7]]])

In [60]:
three_d_array.ndim

3

In [61]:
three_d_array.size

12

In [62]:
three_d_array.shape

(2, 2, 3)

## Indexing and Slicing Arrays - 1

In [63]:
my_arr = np.array([1, 2, 3, 4, 5])

In [66]:
my_arr[0]

np.int64(1)

In [68]:
my_arr[-1]

np.int64(5)

### slicing

In [71]:
my_arr[2:] # starts slicing from 2nd index to last 

array([3, 4, 5])

In [73]:
my_arr[:2] # starts slicing from 0th index to 2nd index

array([1, 2])

In [76]:
my_arr[::2] # start and end value will take as 0 and step is 2 here 

array([1, 3, 5])

#### We can use boolean indexing to retrieve only those values we mark as True. We can mark values in this way by using conditions

In [81]:
ages_list = [1, 18, 20, 23, 24, 25, 27, 8]

In [78]:
# ageages_list >=18 # cannot compare lists to integers 

In [82]:
ages = np.array([ages_list])

In [83]:
ages>=18

array([[False,  True,  True,  True,  True,  True,  True, False]])

In [84]:
ages[ages>=18]

array([18, 20, 23, 24, 25, 27])

#### We can use 'fancy indexing' to select only certain items by index from a NumPy array

In [85]:
my_arr[[3, 0, 1]] # my_arr = array([1, 2, 3, 4, 5])

array([4, 1, 2])

In [87]:
my_arr[[3, 1, 1, 1]]

array([4, 2, 2, 2])

#### We can use np.where() to get the indices where the elements within a NumPy array meet a condition

In [88]:
indices = np.where(my_arr % 2 == 0)

In [89]:
indices # (array([1, 3]),)

(array([1, 3]),)

In [90]:
my_arr[indices] # array([2, 4]), value of the index

array([2, 4])

#### We can use np.where() to modify NumPy arrays

In [92]:
np.where(my_arr > 2, 100, my_arr) # ( condition, case if met , else); does not act in place 

array([  1,   2, 100, 100, 100])

In [94]:
new_arr = np.where(my_arr < 4, my_arr ** 2, -55)

In [96]:
new_arr # array([  1,   4,   9, -55, -55])

array([  1,   4,   9, -55, -55])

#### We can also directly modify NumPy arrays using subscripts

In [97]:
my_arr_2 = my_arr # shallow copy 

In [98]:
my_arr_2

array([1, 2, 3, 4, 5])

In [99]:
my_arr_2[my_arr_2 > 2 ] = 100

In [100]:
my_arr_2

array([  1,   2, 100, 100, 100])

In [101]:
my_arr # array([  1,   2, 100, 100, 100])

array([  1,   2, 100, 100, 100])

In [103]:
my_arr = np.array([1, 2, 3, 4, 5]) # restoring my_arr to its initial values

In [104]:
my_arr

array([1, 2, 3, 4, 5])

In [105]:
my_arr_3 = my_arr.copy()

In [106]:
my_arr_3

array([1, 2, 3, 4, 5])

In [107]:
my_arr_3[my_arr_3 > 2 ] = 100

In [108]:
my_arr_3 # array([  1,   2, 100, 100, 100])

array([  1,   2, 100, 100, 100])

In [109]:
my_arr # array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

#### We can slice multidimensional array by using commas in subscripts

In [110]:
matrix = np.array([[[1, 2, 3], [6, 7, 8]], [[1, 2, 2], [6, 7, 7]]])

In [111]:
matrix

array([[[1, 2, 3],
        [6, 7, 8]],

       [[1, 2, 2],
        [6, 7, 7]]])

In [120]:
matrix[0][1][2] # np.int64(8)

np.int64(8)

In [124]:
my_mat = matrix[matrix > 2]

In [125]:
my_mat

array([3, 6, 7, 8, 6, 7, 7])

In [140]:
matrix[::1]
# array([[[1, 2, 3],
#         [6, 7, 8]],

#        [[1, 2, 2],
#         [6, 7, 7]]])

array([[[1, 2, 3],
        [6, 7, 8]],

       [[1, 2, 2],
        [6, 7, 7]]])

In [139]:
matrix[::2]
# array([[[1, 2, 3],
        # [6, 7, 8]]])

array([[[1, 2, 3],
        [6, 7, 8]]])