In [1]:
import numpy as np

In [2]:
arr = np.array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy']);

In [3]:
arr

array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy'], dtype='<U6')

In [4]:
arr.size

6

You want to better shape this array so that it has different subarrays for each customer

In [8]:
np.reshape(arr, (2, 3)) # np.reshape(a = arr, newshape=(2, 3)) older style

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [9]:
np.reshape(arr, (3, 2))

array([['Ashok', 'Ravi'],
       ['Kumar', 'Shiela'],
       ['P.', 'Reddy']], dtype='<U6')

In [12]:
np.reshape(arr, (1, 1, 6))

array([[['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy']]], dtype='<U6')

In [13]:
np.reshape(arr, (1, 6))

array([['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy']], dtype='<U6')

In [23]:
np.reshape(arr, (3, 1, 2))

array([[['Ashok', 'Ravi']],

       [['Kumar', 'Shiela']],

       [['P.', 'Reddy']]], dtype='<U6')

In [24]:
np.reshape(arr, (6, 1, 1))

array([[['Ashok']],

       [['Ravi']],

       [['Kumar']],

       [['Shiela']],

       [['P.']],

       [['Reddy']]], dtype='<U6')

In [26]:
np.reshape(arr, (-1, 3)) # using -1 will automatically calculate the dimension

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [28]:
np.reshape(arr, (6, -1))

array([['Ashok'],
       ['Ravi'],
       ['Kumar'],
       ['Shiela'],
       ['P.'],
       ['Reddy']], dtype='<U6')

We can transpose NumPy arrays about their axes to flip them around

In [29]:
mat = np.array([['Apple', 'Bread', 'Butter'], [100, 130, 150]])

In [30]:
mat

array([['Apple', 'Bread', 'Butter'],
       ['100', '130', '150']], dtype='<U21')

In [34]:
mat.T # mat.transpose()

array([['Apple', '100'],
       ['Bread', '130'],
       ['Butter', '150']], dtype='<U21')

We can flatten NumPy arrays to one dimension

In [35]:
mat

array([['Apple', 'Bread', 'Butter'],
       ['100', '130', '150']], dtype='<U21')

In [37]:
mat.ravel()

array(['Apple', 'Bread', 'Butter', '100', '130', '150'], dtype='<U21')

In [38]:
mat.flatten()

array(['Apple', 'Bread', 'Butter', '100', '130', '150'], dtype='<U21')

In [39]:
arr = np.arange(24)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [41]:
arr.shape

(24,)

Let's turn into a 4 X 6 , 2D array

In [43]:
reshaped_4x6 = np.reshape(arr, (4, 6))

In [44]:
reshaped_4x6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [45]:
reshaped_4x6.shape

(4, 6)

In [46]:
reshaped_4x6[1, 3]

np.int64(9)

In [47]:
reshaped_2x3x4 = arr.reshape(2, 3, 4)

In [48]:
reshaped_2x3x4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
reshaped_2x3x4[0, 1, 2]

np.int64(6)

In [51]:
reshaped_2x2x2x3 = arr.reshape(2, 2, 2, 3)

In [52]:
reshaped_2x2x2x3

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [53]:
reshaped_2x2x2x3[0, 1, 0, 2]

np.int64(8)

Let's access the elements at (_, _, _, 2) , i.e. the third element of every innermost subarray. Given our dimensions, we can except there to be 8 elements.

In [54]:
reshaped_2x2x2x3[..., 2]

array([[[ 2,  5],
        [ 8, 11]],

       [[14, 17],
        [20, 23]]])

In [56]:
data = np.random.uniform(low = 10, high= 50, size=(365, 5))

In [57]:
data

array([[10.7729052 , 29.22910148, 15.56139191, 46.05549399, 41.55618604],
       [26.20797637, 23.08780149, 22.75575884, 43.38107367, 33.4619044 ],
       [37.37430138, 20.01529127, 32.87686107, 13.01318215, 37.86254425],
       ...,
       [46.01173469, 29.06431829, 32.38428244, 19.44623675, 30.05337652],
       [32.03272968, 34.39145051, 16.14171316, 39.23742281, 13.42953254],
       [41.94981054, 18.13038393, 14.1654575 , 41.33846348, 33.89218252]],
      shape=(365, 5))