In [1]:
sale_us = [4544, 3442, 2334, 1333]
sale_eu = [3544, 4442, 1334, 8333]
sale_in = [5544, 3442, 3334, 9333]

In [5]:
import numpy as np

In [6]:
sales_matrix = np.array ([sale_eu, sale_us, sale_in])

In [7]:
sales_matrix

array([[3544, 4442, 1334, 8333],
       [4544, 3442, 2334, 1333],
       [5544, 3442, 3334, 9333]])

In [8]:
sales_matrix.size

12

In [10]:
sales_matrix.ndim

2

In [11]:
sales_matrix[1:3, 1:3]

array([[3442, 2334],
       [3442, 3334]])

In [12]:
sales_matrix[1:, 1:3]

array([[3442, 2334],
       [3442, 3334]])

In [14]:
np.where(sales_matrix>5000)

(array([0, 2, 2]), array([3, 0, 3]))

In [15]:
sales_matrix[np.where(sales_matrix>5000)]

array([8333, 5544, 9333])

In [16]:
np.where(sales_matrix>5000, "Great Sales", "Bad Sales")

array([['Bad Sales', 'Bad Sales', 'Bad Sales', 'Great Sales'],
       ['Bad Sales', 'Bad Sales', 'Bad Sales', 'Bad Sales'],
       ['Great Sales', 'Bad Sales', 'Bad Sales', 'Great Sales']],
      dtype='<U11')

In [17]:
np.where(sales_matrix>5000, sales_matrix, "Bad Sales")

array([['Bad Sales', 'Bad Sales', 'Bad Sales', '8333'],
       ['Bad Sales', 'Bad Sales', 'Bad Sales', 'Bad Sales'],
       ['5544', 'Bad Sales', 'Bad Sales', '9333']], dtype='<U21')

In [18]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1.5, 10.5)

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [20]:
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr1 = np.arange(1, 13)

In [23]:
np.reshape(arr1, (3, 4), 'C') # follow c programming

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
np.reshape(arr1, (3, 4), 'F') # follows Fortron programming

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])